"""add mystery generation lifecycle and category config

Revision ID: 5267531369ca
Revises: e695179cc28c
Create Date: 2026-09-11 02:28:30.583334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5267531369ca'
down_revision: Union[str, None] = 'e695179cc28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mystery_category_configs',
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mystery_category_configs_category'), 'mystery_category_configs', ['category'], unique=True)
    op.add_column('mysteries', sa.Column('status', sa.String(length=16), server_default='DRAFT', nullable=False))
    op.add_column('mysteries', sa.Column('generator_version', sa.String(length=64), nullable=True))
    op.add_column('mysteries', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # Data backfill (not autogenerated): any mystery that's already live
    # via the pre-existing is_published flag should show as PUBLISHED in
    # the new lifecycle field too, not fall through to the DRAFT default
    # meant for genuinely new rows.
    op.execute("UPDATE mysteries SET status = 'PUBLISHED' WHERE is_published = true")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mysteries', 'rejection_reason')
    op.drop_column('mysteries', 'generator_version')
    op.drop_column('mysteries', 'status')
    op.drop_index(op.f('ix_mystery_category_configs_category'), table_name='mystery_category_configs')
    op.drop_table('mystery_category_configs')
    # ### end Alembic commands ###
