"""add activity tracking and session ended_at

Revision ID: e695179cc28c
Revises: 81466cc9e395
Create Date: 2026-08-31 03:22:10.515537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e695179cc28c'
down_revision: Union[str, None] = '81466cc9e395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_activity_activity_date'), 'user_daily_activity', ['activity_date'], unique=False)
    op.create_index('ix_user_daily_activity_unique', 'user_daily_activity', ['user_id', 'activity_date'], unique=True)
    op.add_column('mystery_sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mystery_sessions', 'ended_at')
    op.drop_index('ix_user_daily_activity_unique', table_name='user_daily_activity')
    op.drop_index(op.f('ix_user_daily_activity_activity_date'), table_name='user_daily_activity')
    op.drop_table('user_daily_activity')
    # ### end Alembic commands ###
